image:
  repository: expediagroup/kubernetes-sidecar-injector
  tag: latest

deployment:
  tpl: {} # template is a keyword
#    annotations:
#      test: test
#    labels:
#      test: test

sidecars:
  dataKey: sidecars.yaml

selectors:
  injectPrefix: sidecar-injector.expedia.com
  injectName: inject
  disableInjectLabel: disable-inject
  objectSelector: {}
  namespaceSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - kube-system
          - kube-public