---
branches:
- master
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
- - "@semantic-release/release-notes-generator"
  - preset: conventionalcommits
- - "@semantic-release/github"
#  - assets:
#    - path: kubernetes-sidecar-injector.darwin.amd64
#      label: Binary - Darwin AMD64
#    - path: kubernetes-sidecar-injector.linux.amd64
#      label: Binary - Linux AMD64
#    - path: kubernetes-sidecar-injector.windows.amd64.exe
#      label: Binary - Windows AMD64