apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}