apiVersion: v1
kind: Service
metadata:
  name: echo-server-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: echo-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app.kubernetes.io/name: echo-server