---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceaccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clusterrole.name" . }}
  labels:
    {{- include "common.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clusterrolebinding.name" . }}
  labels:
    {{- include "common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clusterrole.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "serviceaccount.name" . }}
    namespace: {{ .Release.Namespace }}
