apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
  selector:
    {{- include "common.labels" . | indent 4 }}
