apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    {{- include "common.labels" . | indent 4 }}
