apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ${CSR_NAME}
spec:
  groups:
    - system:authenticated
  request: ${CSR_STR}
  usages:
    - digital signature
    - key encipherment
    - server auth