apiVersion: app/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: kubernetes-sidecar-injector-deployment
  labels:
    app: kubernetes-sidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-sidecar-injector
  template:
    metadata:
      labels:
        app: kubernetes-sidecar-injector
    spec:
      containers:
        - name: kubernetes-sidecar-injector
          image: expediadotcom/kubernetes-sidecar-injector:latest
          imagePullPolicy: IfNotPresent
          args:
            - -port=8443
            - -certFile=/opt/kubernetes-sidecar-injector/certs/cert.pem
            - -keyFile=/opt/kubernetes-sidecar-injector/certs/key.pem
            - -sideCar=/opt/kubernetes-sidecar-injector/sidecarconfig.yaml
            - -logtostderr
            - 2>&1
          volumeMounts:
            - name: kubernetes-sidecar-injector-certs
              mountPath: /opt/kubernetes-sidecar-injector/certs
              readOnly: true
            - name: kubernetes-sidecars-configmap
              mountPath: /opt/kubernetes-sidecar-injector
      volumes:
        - name: kubernetes-sidecar-injector-certs
          secret:
            secretName: kubernetes-sidecar-injector-certs
        - name: kubernetes-sidecars-configmap
          configMap:
            name: kubernetes-sidecars-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-sidecar-injector-svc
  labels:
    app: sidecar-injector
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: kubernetes-sidecar-injector
