name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - uses: actions/checkout@v2

      - name: Unit Test
        run: make test

      - name: Construct Main Docker Tag
        id: docker_tag
        run: echo "::set-output name=tag::v1.0-RC-$(date +'%Y%m%d%H%M%S')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push merge to main
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: expediagroup/kubernetes-sidecar-injector:${{ steps.docker_tag.outputs.tag }},expediagroup/kubernetes-sidecar-injector:latest
