name: Go

on:
  push:
    branches: [ master ]
  pull_request: # Remove
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.11
      - name: Before Install
        run: |
          go get -u github.com/golang/dep/cmd/dep
          go get golang.org/x/tools/cmd/goimports
          go get -u golang.org/x/lint/golint
