name: Deploy

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - uses: actions/checkout@v2
      - name: Unit Test
        run: make test
      - name: Construct PR Docker Tag
        id: docker_tag
        run: echo "::set-output name=tag::$(echo ${{ github.head_ref }} | tr '/' '-')-$(date +'%Y%m%d%H%M%S')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push pull request
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: expediagroup/kubernetes-sidecar-injector:${{ steps.docker_tag.outputs.tag }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows