name: Deploy PR

env:
  GITHUB_OBJECT: |
    ${{ toJson(github) }}

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: tag
        run: echo "::set-output name=tag::$(echo ${{ github.head_ref }} | tr '/' '-')-$(date +'%Y%m%d%H%M%S')"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install requirements
        run: go get -u golang.org/x/lint/golint

      - name: Install
        run: make release

      - name: Deploy
        run: echo ${{ steps.date.outputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.head_ref }}-${{ steps.date.outputs.date }}