name: Helm-Release

on:
  push:
    branches:
      - mvaal/semantic-release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: github-repository
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Set up Go ^1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unit Test
        run: make test

      - name: Code specific changes
        id: code-specific-changes
        uses: tj-actions/changed-files@v23
        with:
          files_ignore: |
            charts
            .github
            .run

      - name: Automated Code Version Bump
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        id: code-version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          commit-message: 'CI: Bump app version to {{version}} [skip ci]'

      - name: Set up Docker Buildx
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push merge to main
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.github-repository.outputs.lowercase }}:${{ steps.code-version-bump.outputs.newTag }}

      - name: Get specific changed files
        id: helm-specific-changes
        uses: tj-actions/changed-files@v23
        with:
          files: |
            charts/kubernetes-sidecar-injector

      - name: Configure Git
        if: steps.helm-specific-changes.outputs.any_modified == 'true'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Automated Helm Version Bump
        if: steps.helm-specific-changes.outputs.any_modified == 'true'
        id: helm-version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          PACKAGEJSON_DIR: charts
        with:
          skip-tag: 'true'
          commit-message: 'CI: Bump Helm chart version to {{version}} [skip ci]'

      - name: update Chart.yaml
        if: steps.helm-specific-changes.outputs.any_modified == 'true'
        working-directory: charts/kubernetes-sidecar-injector
        run: |
          cat <<EOF > Chart.yaml
          name: ${GITHUB_REPOSITORY#*/}
          home: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
          version: ${{ steps.helm-version-bump.outputs.newTag }}
          apiVersion: v2
          keywords:
            - kubernetes
            - sidecar-injection
          EOF

      - name: commit the new Chart.yml
        if: steps.helm-specific-changes.outputs.any_modified == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change [skip ci]
#
#      - name: Install Helm
#        if: steps.helm-specific-changes.outputs.any_modified == 'true'
#        uses: azure/setup-helm@v1
#        with:
#          version: v3.8.0
#
#      - name: Run chart-releaser
#        if: steps.helm-specific-changes.outputs.any_modified == 'true'
#        uses: helm/chart-releaser-action@v1.3.0
#        env:
#          CR_TOKEN: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"