name: Build and Release Container and Helm Chart

on:
  push:
    branches:
      - mvaal/maintenance

jobs:
  release:
    name: Tester
    runs-on: ubuntu-latest
    steps:
      - id: github-repository
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Set up Go ^1.21
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Get specific changed files
        id: helm-specific-changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            charts/kubernetes-sidecar-injector
    
      - name: List all changed files markdown files
        if: steps.helm-specific-changes.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.helm-specific-changes.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done